name: Build NXI Ads Full ZIP

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, intl, mysqli, zip

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build & Package
        run: |
          mkdir -p build
          zip -r build/NXI-Ads-Full-System.zip . -x ".git*" -x "node_modules/*" -x ".github/*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NXI-Ads-Full-System
          path: build/NXI-Ads-Full-System.zip
